// <auto-generated />
using System;
using System.Collections.Generic;
using AgentBridge.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentBridge.Persistence.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(AgentBridgeDbContext))]
    [Migration("20261004074347_AddDurableToolAttempts")]
    partial class AddDurableToolAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.CanonicalItemRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DialogId", "TurnId", "Sequence");

                    b.ToTable("CanonicalItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_Item_Sequence", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogContextRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("ThroughTurnSequence")
                        .HasColumnType("bigint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Compaction", "AgentBridge.Persistence.EfCore.Models.DialogContextRecord.Compaction#ModelResponseRecord", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContinuationJson")
                                .HasColumnType("text")
                                .HasColumnName("ResponseContinuationJson");

                            b1.Property<string>("EnvelopeJson")
                                .HasColumnType("text")
                                .HasColumnName("ResponseEnvelopeJson");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("ResponseErrorMessage");

                            b1.Property<int?>("ErrorType")
                                .HasColumnType("integer")
                                .HasColumnName("ResponseErrorType");

                            b1.Property<int>("FormatVersion")
                                .HasColumnType("integer")
                                .HasColumnName("ResponseFormatVersion");

                            b1.Property<string>("OutputJson")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ResponseOutputJson");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("ResponseStatus");
                        });

                    b.HasKey("DialogId", "Version");

                    b.ToTable("DialogContexts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Context_Completed", "\"ResponseStatus\" = 0");

                            t.HasCheckConstraint("CK_Context_Prefix", "\"ThroughTurnSequence\" >= 0");

                            t.HasCheckConstraint("CK_Context_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_DialogContextRecord_ResponseError", "(\"ResponseStatus\" = 2 AND \"ResponseErrorType\" IS NOT NULL AND \"ResponseErrorType\" BETWEEN 0 AND 8 AND \"ResponseErrorMessage\" IS NOT NULL AND length(\"ResponseErrorMessage\") > 0) OR (\"ResponseStatus\" <> 2 AND \"ResponseErrorType\" IS NULL AND \"ResponseErrorMessage\" IS NULL)");

                            t.HasCheckConstraint("CK_DialogContextRecord_ResponseStatus", "\"ResponseStatus\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_DialogContextRecord_ResponseVersion", "\"ResponseFormatVersion\" = 1");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ContentBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpiresAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("IncarnationId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<long>("LastChangedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc", "Id");

                    b.ToTable("Dialogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Dialog_ContentBytes", "\"ContentBytes\" >= 0");

                            t.HasCheckConstraint("CK_Dialog_Expiry", "\"ExpiresAtUtc\" > \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_Dialog_Identity", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"IncarnationId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Dialog_LastChanged", "\"LastChangedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_Dialog_Owner", "length(\"OwnerId\") > 0");

                            t.HasCheckConstraint("CK_Dialog_Revision", "\"Revision\" >= 0");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("FinishedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("DialogId", "Id");

                    b.HasIndex("DialogId", "Sequence")
                        .IsUnique();

                    b.ToTable("DialogTurns", null, t =>
                        {
                            t.HasCheckConstraint("CK_Turn_Finished", "(\"Status\" = 0 AND \"FinishedAtUtc\" IS NULL) OR (\"Status\" <> 0 AND \"FinishedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" >= \"StartedAtUtc\")");

                            t.HasCheckConstraint("CK_Turn_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_Turn_Status", "\"Status\" BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.ModelStepRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ToolAttemptsJson")
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Response", "AgentBridge.Persistence.EfCore.Models.ModelStepRecord.Response#ModelResponseRecord", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContinuationJson")
                                .HasColumnType("text")
                                .HasColumnName("ResponseContinuationJson");

                            b1.Property<string>("EnvelopeJson")
                                .HasColumnType("text")
                                .HasColumnName("ResponseEnvelopeJson");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("ResponseErrorMessage");

                            b1.Property<int?>("ErrorType")
                                .HasColumnType("integer")
                                .HasColumnName("ResponseErrorType");

                            b1.Property<int>("FormatVersion")
                                .HasColumnType("integer")
                                .HasColumnName("ResponseFormatVersion");

                            b1.Property<string>("OutputJson")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ResponseOutputJson");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("ResponseStatus");
                        });

                    b.HasKey("DialogId", "TurnId", "Id");

                    b.HasIndex("DialogId", "TurnId", "Sequence")
                        .IsUnique();

                    b.ToTable("ModelSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_ModelStepRecord_ResponseError", "(\"ResponseStatus\" = 2 AND \"ResponseErrorType\" IS NOT NULL AND \"ResponseErrorType\" BETWEEN 0 AND 8 AND \"ResponseErrorMessage\" IS NOT NULL AND length(\"ResponseErrorMessage\") > 0) OR (\"ResponseStatus\" <> 2 AND \"ResponseErrorType\" IS NULL AND \"ResponseErrorMessage\" IS NULL)");

                            t.HasCheckConstraint("CK_ModelStepRecord_ResponseStatus", "\"ResponseStatus\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_ModelStepRecord_ResponseVersion", "\"ResponseFormatVersion\" = 1");

                            t.HasCheckConstraint("CK_Step_Sequence", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.CanonicalItemRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId", "TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogContextRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.ModelStepRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId", "TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
