// <auto-generated />
using System;
using System.Collections.Generic;
using AgentBridge.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentBridge.Persistence.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(AgentBridgeDbContext))]
    [Migration("20261006060948_InitialAgentBridgeSchema")]
    partial class InitialAgentBridgeSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.CanonicalItemRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DialogId", "TurnId", "Sequence");

                    b.ToTable("CanonicalItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_Item_Sequence", "[Sequence] > 0");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogContextRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("SelectedModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ThroughTurnSequence")
                        .HasColumnType("bigint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Compaction", "AgentBridge.Persistence.EfCore.Models.DialogContextRecord.Compaction#ModelResponseRecord", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContinuationJson")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseContinuationJson");

                            b1.Property<string>("EnvelopeJson")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseEnvelopeJson");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseErrorMessage");

                            b1.Property<int?>("ErrorType")
                                .HasColumnType("int")
                                .HasColumnName("ResponseErrorType");

                            b1.Property<int>("FormatVersion")
                                .HasColumnType("int")
                                .HasColumnName("ResponseFormatVersion");

                            b1.Property<string>("OutputJson")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseOutputJson");

                            b1.Property<int>("Status")
                                .HasColumnType("int")
                                .HasColumnName("ResponseStatus");
                        });

                    b.HasKey("DialogId", "Version");

                    b.ToTable("DialogContexts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Context_Completed", "[ResponseStatus] = 0");

                            t.HasCheckConstraint("CK_Context_Prefix", "[ThroughTurnSequence] >= 0");

                            t.HasCheckConstraint("CK_Context_Version", "[Version] > 0");

                            t.HasCheckConstraint("CK_DialogContextRecord_ResponseError", "([ResponseStatus] = 2 AND [ResponseErrorType] IS NOT NULL AND [ResponseErrorType] BETWEEN 0 AND 8 AND [ResponseErrorMessage] IS NOT NULL AND DATALENGTH([ResponseErrorMessage]) > 0) OR ([ResponseStatus] <> 2 AND [ResponseErrorType] IS NULL AND [ResponseErrorMessage] IS NULL)");

                            t.HasCheckConstraint("CK_DialogContextRecord_ResponseStatus", "[ResponseStatus] BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_DialogContextRecord_ResponseVersion", "[ResponseFormatVersion] = 1");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ContentBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpiresAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("IncarnationId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastChangedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("OwnerId")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc", "Id");

                    b.ToTable("Dialogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Dialog_ContentBytes", "[ContentBytes] >= 0");

                            t.HasCheckConstraint("CK_Dialog_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_Dialog_Identity", "[Id] <> '00000000-0000-0000-0000-000000000000' AND [IncarnationId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Dialog_LastChanged", "[LastChangedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_Dialog_Owner", "DATALENGTH([OwnerId]) > 0");

                            t.HasCheckConstraint("CK_Dialog_Revision", "[Revision] >= 0");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogSettingsRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Effort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DialogSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Settings_Effort", "DATALENGTH([Effort]) > 0");

                            t.HasCheckConstraint("CK_Settings_Model", "DATALENGTH([Model]) > 0");

                            t.HasCheckConstraint("CK_Settings_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FinishedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DialogId", "Id");

                    b.HasIndex("DialogId", "Sequence")
                        .IsUnique();

                    b.ToTable("DialogTurns", null, t =>
                        {
                            t.HasCheckConstraint("CK_Turn_Finished", "([Status] = 0 AND [FinishedAtUtc] IS NULL) OR ([Status] <> 0 AND [FinishedAtUtc] IS NOT NULL AND [FinishedAtUtc] >= [StartedAtUtc])");

                            t.HasCheckConstraint("CK_Turn_Sequence", "[Sequence] > 0");

                            t.HasCheckConstraint("CK_Turn_Status", "[Status] BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.ModelStepRecord", b =>
                {
                    b.Property<Guid>("DialogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ToolAttemptsJson")
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Response", "AgentBridge.Persistence.EfCore.Models.ModelStepRecord.Response#ModelResponseRecord", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContinuationJson")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseContinuationJson");

                            b1.Property<string>("EnvelopeJson")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseEnvelopeJson");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseErrorMessage");

                            b1.Property<int?>("ErrorType")
                                .HasColumnType("int")
                                .HasColumnName("ResponseErrorType");

                            b1.Property<int>("FormatVersion")
                                .HasColumnType("int")
                                .HasColumnName("ResponseFormatVersion");

                            b1.Property<string>("OutputJson")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResponseOutputJson");

                            b1.Property<int>("Status")
                                .HasColumnType("int")
                                .HasColumnName("ResponseStatus");
                        });

                    b.HasKey("DialogId", "TurnId", "Id");

                    b.HasIndex("DialogId", "TurnId", "Sequence")
                        .IsUnique();

                    b.ToTable("ModelSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_ModelStepRecord_ResponseError", "([ResponseStatus] = 2 AND [ResponseErrorType] IS NOT NULL AND [ResponseErrorType] BETWEEN 0 AND 8 AND [ResponseErrorMessage] IS NOT NULL AND DATALENGTH([ResponseErrorMessage]) > 0) OR ([ResponseStatus] <> 2 AND [ResponseErrorType] IS NULL AND [ResponseErrorMessage] IS NULL)");

                            t.HasCheckConstraint("CK_ModelStepRecord_ResponseStatus", "[ResponseStatus] BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_ModelStepRecord_ResponseVersion", "[ResponseFormatVersion] = 1");

                            t.HasCheckConstraint("CK_Step_Sequence", "[Sequence] > 0");
                        });
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.CanonicalItemRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId", "TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogContextRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogSettingsRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogRecord", null)
                        .WithOne()
                        .HasForeignKey("AgentBridge.Persistence.EfCore.Models.DialogSettingsRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentBridge.Persistence.EfCore.Models.ModelStepRecord", b =>
                {
                    b.HasOne("AgentBridge.Persistence.EfCore.Models.DialogTurnRecord", null)
                        .WithMany()
                        .HasForeignKey("DialogId", "TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
